
# experiment name
exp_name : "eval_approx_strategies/mix"

# training
train : True
kl_weight: 1e-6
train_samples: 10

# test
ood : True
missing_data_imputation : False
test_samples: 100

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 24
    
# model
pretrained : False
no_conv : False
latent_size : 2

# hessian
backend : "layer" 
approximation : "mix"
