
# experiment name
exp_name : "ood_experiment/"

# training
train : True
train_samples: 1

# test
ood : True
test_samples: 100

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2