# experiment name
exp_name : "ood_experiment/"

# training
train : True
posthoc : False
alpha: 0
train_samples: 1
prior_precision: 1

# test
ood : True
missing_data_imputation : False
test_samples: 100

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2

# hessian
backend : "layer" 
approximation : "exact" #block, exact, diag, mix
hessian_memory_factor : 0.999
one_hessian_per_sampling : False
update_hessian : True
hessian_scale : 1