# experiment name
exp_name : "ood_experiment/large_model_repro"

# training
train : True
posthoc : False
alpha: 0
train_samples: 1
prior_precision: 1
learning_rate: 1e-4

# test
ood : True
test_samples: 10

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 100

# model
pretrained : False
no_conv : False
latent_size : 2

# hessian
backend : "layer" 
approximation : "mix" #block, exact, diag, mix
hessian_memory_factor : 0.999
one_hessian_per_sampling : False
update_hessian : True
hessian_scale : 1