
# experiment name
exp_name : ""

# training
train : False
kl_weight: 1e-6
train_samples: 10

# test
ood : False
missing_data_imputation : False
test_samples: 100

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 24
    
# model
pretrained : False
no_conv : False
latent_size : 2

# hessian
backend : "layer" # choose layer, row, backpack
diag : False
