
# training
train : True

# test
test_samples: 100

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size : 128
    
# model
use_la_encoder : False # this will fit the laplace to both encoder and decoder