
# experiment name
exp_name : "linear_exact_med/"

# training
train : True
kl_weight: 1e-6
train_samples: 5

# test
ood : True
missing_data_imputation : False
test_samples: 100

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 10
    
# model
pretrained : False
no_conv : True
latent_size : 2

# hessian
backend : "layer" 
approximation : "exact" #block, exact, diag, mix
hessian_memory_factor : 0.9
one_hessian_per_sampling : True
